### PR TITLE
Composite metadata & fire_and_forget, metadata_push support

### PR DESCRIPTION
**Pull request by linux-china**

### CODE REVIEW

**Comment by OlegDokuka** [comment]
Will take a look at that later this week

**Comment by belkirdi** [comment]
@OlegDokuka @linux-china Welcome back guys !!! any new updates about rsocket python ?

**Comment by linux-china** [comment]
> @OlegDokuka @linux-china Welcome back guys !!! any new updates about rsocket python ? I saw lot of codes commited related to fire and forget and metadata push any plan for request stream and request channel ?

Yes, it's on my list, and you know I'm not Python expert. :)  
A good news for you, now an internal product is using RSocket Python but focus on request/response with high QPS every day and it's stable now.   Load Balance is on the way too, and give us some time :)

**Comment by belkirdi** [comment]
> > @OlegDokuka @linux-china Welcome back guys !!! any new updates about rsocket python ? I saw lot of codes commited related to fire and forget and metadata push any plan for request stream and request channel ?
> 
> Yes, it's on my list, and you know I'm not Python expert. :)
> A good news for you, now an internal product is using RSocket Python but focus on request/response with high QPS every day and it's stable now. Load Balance is on the way too, and give us some time :)

That's a really great news I am really excited to implement rsocket python client in our project !! Do you have any forked repository that I can look at too and work with you if you want..

**Comment by tkumar9** [comment]
Is request stream implemented?

**Comment by linux-china** [comment]
> Is request stream implemented?
> Why this pull request is not merged? can we use this branch?

yes,  request_stream has been implemented, and you can use this branch.

**Comment by tkumar9** [comment]
> > Is request stream implemented?
> > Why this pull request is not merged? can we use this branch?
> 
> yes, request_stream has been implemented, and you can use this branch.

thanks a lot. Can you please advise how can I download this code as I see only master branch. Can you please merge all your changes to master branch?
Is protobuf payload supported for client implemantation?
Can you please also include some request_stream client examples?

Appriciete your help.

**Comment by tkumar9** [comment]
> > > > Is request stream implemented?
> > > > Why this pull request is not merged? can we use this branch?
> > > 
> > > 
> > > yes, request_stream has been implemented, and you can use this branch.
> > 
> > 
> > thanks a lot. Can you please advise how can I download this code as I see only master branch. Can you please merge all your changes to master branch?
> > Is protobuf payload supported for client implemantation?
> > Can you please also include some request_stream client examples?
> > Appriciete your help.
> 
> Now you can get code from https://github.com/linux-china/rsocket-py and request_stream example has been included.
> 
> ```python
> class Handler(BaseRequestHandler):
> 
>     def request_fire_and_forget(self, payload: Payload):
>         print("received fir_and_forget: ", payload.data)
> 
>     def request_response(self, payload: Payload) -> asyncio.Future:
>         future = asyncio.Future()
>         future.set_result(Payload(
>             b'The quick brown fox jumps over the lazy dog.',
>             b'Escher are an artist.'))
>         return future
> 
>     def request_stream(self, payload: Payload) -> Publisher:
>         return FluxProcessor.from_list([Payload(b'data1', b'metadata'), Payload(b'data2', b'metadata')])
> ```

thank a lot for helping. can you please merge this PR to official python master branch also.

**Comment by balajij81** [comment]
Can you someone please review and merge this pull request to the master branch ? It is open for 2 years we have genuine use this now ?

**Comment by balajij81** [comment]
> Will take a look at that later this week

@OlegDokuka Can you please review this and merge the change if needed please provide write access I can merge this change as well.

**Pull request closed without merging**
